name: Code Style

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Code Style
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel